### ISSUE TITLE
V4MD should include xtend.lib 2.12

### ISSUE THREAD

**Issue by lunkpeter** [viatra/v4md#1]
As the user might use V4MD to execute queries, which contain a check expression in a separate MD plugin. In this case the user explicitly needs to add the xtend lib dependency otherwise the xtend lib elements required by check expressions will not be present on the classpath.

**Comment by ujhelyiz** [comment]
Xtend lib 2.13 is included in the latest builds. This can be targeted both by Xtext 2.12 and 2.13.
