### ISSUE TITLE
Erroneous line in plugin.xml

### ISSUE THREAD

**Issue by lunkpeter** [viatra/v4md#11]
class="com.incquerylabs.v4md.V4MDPlugin"
class-lookup="GlobalFirst"
ownClassloader="false"
id="com.incquerylabs.v4md"
name="V4MD"
internalVersion="${internal.version}"
version="${human.version}"
provider-name="IncQuery Labs Ltd."
**licenseId="IncQuery for MagicDraw">**

**Comment by ujhelyiz** [comment]
Fixed.
