### ISSUE TITLE
Erroneous descriptor.xml generated during build

### ISSUE THREAD

**Issue by lunkpeter** [viatra/v4md#16]
```
<?xml version="1.0" encoding="UTF-8"?>
<resourceDescriptor critical="false"
                    date="2018-10-26-16:46"
                    description="MagicDraw plug-in for incremental pattern matching and validation."
                    id="1720"
                    mdVersionMax="higher"
                    mdVersionMin="18.0"
                    name="V4MD"
                    homePage="https://github.com/viatra/v4md"
                    product="V4MD"
                    type="Plugin">
    <version human="2.0.4" resource="2040100" internal="204010"/>
    <provider name="IncQuery Labs Ltd."/>
    <edition>Reader</edition>
    <edition>Community</edition>
    <edition>Standard</edition>
    <edition>Professional Java</edition>
    <edition>Professional C++</edition>
    <edition>Professional C#</edition>
    <edition>Professional ArcStyler</edition>
    <edition>Professional EFFS ArcStyler</edition>
    <edition>OptimalJ</edition>
    <edition>Professional</edition>
    <edition>Architect</edition>
    <edition>Enterprise</edition>
    
    <installation>
        <!-- START AUTO-GENERATED -->

		<file from=".." to=".."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>
		<file from="../../.." to="../../.."/>

        <!-- END AUTO-GENERATED -->
    </installation>
</resourceDescriptor>
```

**Comment by ujhelyiz** [comment]
Should be fixed. Can you check https://build.incquerylabs.com/nexus/repository/v4md/com/incquerylabs/v4md/com.incquerylabs.v4md/2.0.5-SNAPSHOT/com.incquerylabs.v4md-2.0.5-20181027.083543-1-plugin.zip

Thanks.

**Comment by lunkpeter** [comment]
the snapshot build contains two versions of the plugin jar

		<file from="EULA_V4MD.txt" to="EULA_V4MD.txt"/>
		<file from="data/resourcemanager/MDR_Plugin_V4MD_1720_descriptor.xml" to="data/resourcemanager/MDR_Plugin_V4MD_1720_descriptor.xml"/>
		<file from="plugins/com.incquerylabs.v4md/viatra-query-runtime-2.0.2.jar" to="plugins/com.incquerylabs.v4md/viatra-query-runtime-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.transformationtrace-0.20.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.transformationtrace-0.20.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.xtend.lib-2.12.0.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.xtend.lib-2.12.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.matchers-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.matchers-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/plugin.xml" to="plugins/com.incquerylabs.v4md/plugin.xml"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.base.itc-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.base.itc-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.xtext.xbase.lib-2.12.0.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.xtext.xbase.lib-2.12.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.base-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.base-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.rete-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.rete-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/viatra-transformation-runtime-2.0.2.jar" to="plugins/com.incquerylabs.v4md/viatra-transformation-runtime-2.0.2.jar"/>
		**<file from="plugins/com.incquerylabs.v4md/com.incquerylabs.v4md-2.0.5-SNAPSHOT.jar" to="plugins/com.incquerylabs.v4md/com.incquerylabs.v4md-2.0.5-SNAPSHOT.jar"/>**
		<file from="plugins/com.incquerylabs.v4md/guava-18.0.jar" to="plugins/com.incquerylabs.v4md/guava-18.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.evm-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.evm-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.debug-0.20.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.debug-0.20.2.jar"/>
		**<file from="plugins/com.incquerylabs.v4md/com.incquerylabs.v4md-2.0.4-SNAPSHOT.jar" to="plugins/com.incquerylabs.v4md/com.incquerylabs.v4md-2.0.4-SNAPSHOT.jar"/>**
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.xtend.lib.macro-2.12.0.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.xtend.lib.macro-2.12.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/eclipse-collections-9.0.0.jar" to="plugins/com.incquerylabs.v4md/eclipse-collections-9.0.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.rete.recipes-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.rete.recipes-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/eclipse-collections-api-9.0.0.jar" to="plugins/com.incquerylabs.v4md/eclipse-collections-api-9.0.0.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.emf-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.transformation.runtime.emf-2.0.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/viatra-transformation-debugger-runtime-0.20.2.jar" to="plugins/com.incquerylabs.v4md/viatra-transformation-debugger-runtime-0.20.2.jar"/>
		<file from="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.localsearch-2.0.2.jar" to="plugins/com.incquerylabs.v4md/org.eclipse.viatra.query.runtime.localsearch-2.0.2.jar"/>

**Comment by lunkpeter** [comment]
Also both 2.0.4 and 2.0.5 is present in the zip
![image](https://user-images.githubusercontent.com/3957526/47601981-565e8b00-d9d8-11e8-8cfd-49992d06334c.png)

**Comment by ujhelyiz** [comment]
Note for the future, as opposed to Maven the `clean` task of Gradle does not empty the entire gradle build output folder, only the folders explicitly specified by the codebase...

To me, https://build.incquerylabs.com/nexus/repository/v4md-snapshots/com/incquerylabs/v4md/com.incquerylabs.v4md/2.0.5-SNAPSHOT/com.incquerylabs.v4md-2.0.5-20181027.092331-2-plugin.zip seems to be fixed.
