### ISSUE TITLE
ViatraQueryAdapter engine scope is not updated when new project usage is added

### ISSUE THREAD

**Issue by lunkpeter** [viatra/v4md#25]
VQA Engine scope should be updated when project dependencies are change. Preferrably this should be done automatically, but the plugin should provide API for adding scope elements manually too.

**Comment by ujhelyiz** [comment]
A first fix candidate was merged into master (I planned to open a PR, but misclicked in Eclipse... I will not revert the change, but apply any future fixes as necessary) that automatically updates the Base index settings when the model is updated.

@debrecenics promised to test the build on Monday.

**Comment by lunkpeter** [comment]
@debrecenics please check this

**Comment by debrecenics** [comment]
I checked it and it works for me
