### ISSUE TITLE
Provide UI functionality to dispose query engines

### ISSUE THREAD

**Issue by ujhelyiz** [viatra/v4md#42]
We should add a (hidden by default) menu item to MagicDraw that allows the user to dispose of the ViatraQueryEngine instances using ViatraQueryAdapter#dispose (it is allowed to cause side-effects for existing users).

This functionality should only be available when MagicDraw was started in DEVELOPER mode.

**Comment by debrecenics** [comment]
Minor improvements are required
- [ ] pop-up window with a warning
- [ ] only in developer mode

**Comment by ujhelyiz** [comment]
Reopening the issue to track replacing query backends to avoid the creation of internal Rete structures.

**Comment by ujhelyiz** [comment]
Second iteration added a NopQueryBackend to use when indexes are turned off. This solution avoids internal query backend related structures, such as Rete networks to be calculated and initialized.
