### ISSUE TITLE
Error message "Can not modify frozen property"

### ISSUE THREAD

**Issue by debrecenics** [viatra/v4md#72]
The following error appeared when V4MD is used
[MDUML-119283.docx](https://github.com/viatra/v4md/files/6420259/MDUML-119283.docx)

`2021-04-28 15:54:25,463 [main] [ ] ERROR GENERAL - Can not modify frozen property com.nomagic.magicdraw.properties.BooleanProperty@b7f482f3 USE_EMPTY_QUERY_SCOPE false (undefined state - false) java.lang.IllegalStateException: Can not modify frozen property com.nomagic.magicdraw.properties.BooleanProperty@b7f482f3 USE_EMPTY_QUERY_SCOPE false (undefined state - false) at com.nomagic.magicdraw.properties.Property.checkFrozen(Property.java:1057) [md_api.jar:?] at com.nomagic.magicdraw.properties.Property.checkFrozen(Property.java:1041) [md_api.jar:?] at com.nomagic.magicdraw.properties.Property.setEditable(Property.java:731) [md_api.jar:?] at com.incquerylabs.v4md.V4MDSpecificEnvironmentOptionsGroup.setEditability (V4MDSpecificEnvironmentOptionsGroup.java:123) [com.incquerylabs.v4md-2.5.1.jar:?] at com.incquerylabs.v4md.V4MDSpecificEnvironmentOptionsGroup.loadOptions (V4MDSpecificEnvironmentOptionsGroup.java:71) [com.incquerylabs.v4md-2.5.1.jar:?]`

**Comment by debrecenics** [comment]
aa50f07 proposes a short workaround for this issue. When the environment option is frozen, we (1) unfreeze it, (2) make it (un)editable, (3) freeze it back. However, the problem with this solution is that internal API is heavily used.

Alternatively, we need to find another way to present such environment option to users.

**Comment by ujhelyiz** [comment]
We have discussed this issue internally, and we will handle this issue as follows:

- We will keep the property structure but will not require developer mode.
- This should avoid the freeze/read-only settings issue, as we can rely on the default behavior.
- We should notify the users that the engine is started with empty scope to avoid them not turning this functionality off when not necessary anymore.
