### ISSUE TITLE
Errors in Jenkinsfile on 2022x and 2024x branches

### ISSUE THREAD

**Issue by TheKorpos** [viatra/v4md#86]
# 2022x and 2024x
remove the dir switching. We need to run publish from root project
https://github.com/viatra/v4md/blob/63195bd108b518b39b1f9ad3b4588f68afeb3eb3/Jenkinsfile#L45

# 2024x
change branch name in publising from 2022x to 2024x
https://github.com/viatra/v4md/blob/2dd56659b4c3bfcd8f78b94ea48e809acd95642b/Jenkinsfile#L41

**Comment by ujhelyiz** [comment]
Fixed in both branches.
